// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `logging.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <stdafx.h>
#include <logging.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Logging__RemoteLog__log_name = "log";

}
::IceProxy::Ice::Object* ::IceProxy::Logging::upCast(::IceProxy::Logging::RemoteLog* p) { return p; }

void
::IceProxy::Logging::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Logging::RemoteLog>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Logging::RemoteLog;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Logging::RemoteLog::log(const ::std::string& name, const ::std::string& time, const ::std::string& msg, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Logging__RemoteLog__log_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Logging::RemoteLog* __del = dynamic_cast< ::IceDelegate::Logging::RemoteLog*>(__delBase.get());
            __del->log(name, time, msg, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Logging::RemoteLog::begin_log(const ::std::string& name, const ::std::string& time, const ::std::string& msg, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Logging__RemoteLog__log_name, __del, __cookie);
    try
    {
        __result->__prepare(__Logging__RemoteLog__log_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(time);
        __os->write(msg);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Logging::RemoteLog::end_log(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Logging__RemoteLog__log_name);
}

const ::std::string&
IceProxy::Logging::RemoteLog::ice_staticId()
{
    return ::Logging::RemoteLog::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Logging::RemoteLog::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Logging::RemoteLog);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Logging::RemoteLog::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Logging::RemoteLog);
}

::IceProxy::Ice::Object*
IceProxy::Logging::RemoteLog::__newInstance() const
{
    return new RemoteLog;
}

void
IceDelegateM::Logging::RemoteLog::log(const ::std::string& name, const ::std::string& time, const ::std::string& msg, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Logging__RemoteLog__log_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(name);
        __os->write(time);
        __os->write(msg);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::Logging::RemoteLog::log(const ::std::string& name, const ::std::string& time, const ::std::string& msg, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_name, const ::std::string& __p_time, const ::std::string& __p_msg, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_name(__p_name),
            _m_time(__p_time),
            _m_msg(__p_msg)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Logging::RemoteLog* servant = dynamic_cast< ::Logging::RemoteLog*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->log(_m_name, _m_time, _m_msg, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_name;
        const ::std::string& _m_time;
        const ::std::string& _m_msg;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Logging__RemoteLog__log_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(name, time, msg, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* Logging::upCast(::Logging::RemoteLog* p) { return p; }

namespace
{
const ::std::string __Logging__RemoteLog_ids[2] =
{
    "::Ice::Object",
    "::Logging::RemoteLog"
};

}

bool
Logging::RemoteLog::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Logging__RemoteLog_ids, __Logging__RemoteLog_ids + 2, _s);
}

::std::vector< ::std::string>
Logging::RemoteLog::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Logging__RemoteLog_ids[0], &__Logging__RemoteLog_ids[2]);
}

const ::std::string&
Logging::RemoteLog::ice_id(const ::Ice::Current&) const
{
    return __Logging__RemoteLog_ids[1];
}

const ::std::string&
Logging::RemoteLog::ice_staticId()
{
    return __Logging__RemoteLog_ids[1];
}

::Ice::DispatchStatus
Logging::RemoteLog::___log(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string name;
    ::std::string time;
    ::std::string msg;
    __is->read(name);
    __is->read(time);
    __is->read(msg);
    __inS.endReadParams();
    log(name, time, msg, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Logging__RemoteLog_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "log"
};

}

::Ice::DispatchStatus
Logging::RemoteLog::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Logging__RemoteLog_all, __Logging__RemoteLog_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Logging__RemoteLog_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___log(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Logging::RemoteLog::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Logging::RemoteLog::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Logging::__patch(RemoteLogPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Logging::RemoteLogPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Logging::RemoteLog::ice_staticId(), v);
    }
}
